# generated by datamodel-codegen:
#   filename:  wipp-plugin-manifest-schema.json
#   timestamp: 2021-03-19T01:44:25+00:00

from __future__ import annotations

from typing import Any, List, Optional, Union

from pydantic import BaseModel, Field, constr
from ._io import Input, Output, Version


class UiItem(BaseModel):
    key: Union[Any, Any] = Field(
        ...,
        description="Key of the input which this UI definition applies to, the expected format is 'inputs.inputName'. Special keyword 'fieldsets' can be used to define arrangement of inputs by sections.",
        examples=["inputs.inputImages", "inputs.fileNamPattern", "fieldsets"],
    )
    title: str
    description: str


class WIPPPluginManifest(BaseModel):
    name: constr(regex=r"^(.*)$", min_length=1) = Field(  # noqa: F722
        ..., examples=["My Awesome Plugin"], title="Name of the plugin"
    )
    version: Version
    title: constr(regex=r"^(.*)$", min_length=1) = Field(  # noqa: F722
        ..., examples=["My really awesome plugin"], title="Plugin title"
    )
    description: constr(regex=r"^(.*)$", min_length=1) = Field(  # noqa: F722
        ..., examples=["My awesome segmentation algorithm"], title="Description"
    )
    author: Optional[Optional[constr(regex=r"^(.*)$")]] = Field(  # noqa: F722
        "", examples=["FirstName LastName"], title="Author(s)"
    )
    institution: Optional[Optional[constr(regex=r"^(.*)$")]] = Field(  # noqa: F722
        "",
        examples=["National Institute of Standards and Technology"],
        title="Institution",
    )
    repository: Optional[Optional[str]] = Field(
        "",
        examples=["https://github.com/usnistgov/WIPP"],
        title="Source code repository",
    )
    website: Optional[Optional[str]] = Field(
        "", examples=["http://usnistgov.github.io/WIPP"], title="Website"
    )
    citation: Optional[Optional[constr(regex=r"^(.*)$")]] = Field(  # noqa: F722
        "",
        examples=[
            "Peter Bajcsy, Joe Chalfoun, and Mylene Simon (2018). Web Microanalysis of Big Image Data. Springer-Verlag International"
        ],
        title="Citation",
    )
    containerId: constr(regex=r"^(.*)$") = Field(  # noqa: F722
        ...,
        description="Docker image ID",
        examples=["wipp/example-plugin:1.0.0"],
        title="ContainerId",
    )
    inputs: List[Input] = Field(
        ..., description="Defines inputs to the plugin", title="List of Inputs"
    )
    outputs: List[Output] = Field(
        ..., description="Defines the outputs of the plugin", title="List of Outputs"
    )
    ui: List[UiItem] = Field(..., title="Plugin form UI definition")

    # @validator("version", pre=True)
    # def cast_version(cls, value):
    #     return utils_cast_version(value)
