[mypy]
files = src/polus/images/formats/ome_converter, tests/
exclude = \.git/
disable_error_code = import-untyped

[mypy-bfio]
ignore_missing_imports = True

[mypy-filepattern]
ignore_missing_imports = True

[mypy-tqdm]
ignore_missing_imports = True

# [mypy-polus.images.formats.ome_converter.*]
# ignore_missing_imports = False
