FROM ubuntu:latest

RUN apt-get -y update && apt-get -y install g++ make wget
RUN mkdir -p /home/DistributedKNN

COPY . /home/DistributedKNN
WORKDIR /home/DistributedKNN

RUN wget https://download.open-mpi.org/release/open-mpi/v4.0/openmpi-4.0.0.tar.gz
RUN tar xfz openmpi-4.0.0.tar.gz
RUN rm openmpi-4.0.0.tar.gz
WORKDIR /home/DistributedKNN/openmpi-4.0.0
RUN ./configure
RUN make all install
ENV LD_LIBRARY_PATH="/usr/local/lib:${LD_LIBRARY_PATH}"
ENV PATH="/usr/local/bin:${PATH}"

WORKDIR /home/DistributedKNN
RUN wget https://dl.bintray.com/boostorg/release/1.71.0/source/boost_1_71_0.tar.gz
RUN tar xfz boost_1_71_0.tar.gz 
RUN rm boost_1_71_0.tar.gz
WORKDIR /home/DistributedKNN/boost_1_71_0
RUN ./bootstrap.sh
RUN ./b2
ENV LD_LIBRARY_PATH="/home/DistributedKNN/boost_1_71_0/stage/lib:${LD_LIBRARY_PATH}"

WORKDIR /home/DistributedKNN
RUN mpicxx -I/home/DistributedKNN/boost_1_71_0 KNN_Distributed_code-OpenMP.cpp -o output.exe -L/home/DistributedKNN/boost_1_71_0/stage/lib -lboost_iostreams -O2 -fopenmp
ENV OMP_NUM_THREADS=2
ENTRYPOINT ["mpirun","-np","4","./output.exe"]
