"""Extending automatically generated compute model.

This file modifies and extend certain fields and
functions of PolusComputeSchema.py which is automatically
generated by datamodel-codegen from JSON schema.
"""
from typing import List

from polus.plugins._plugins.io import IOBase, Version
from polus.plugins._plugins.models.PolusComputeSchema import (  # CustomUIType, ????; CLTSchema ????
    ConditionEntry,
    GpuVendor,
    PluginHardwareRequirements,
    PluginInput,
    PluginInputType,
    PluginOutput,
    PluginOutputType,
    PluginSchema,
    PluginUIInput,
    PluginUIOutput,
    PluginUIType,
    ThenEntry,
    Validator,
)


class PluginInput(PluginInput, IOBase):
    pass


class PluginOutput(PluginOutput, IOBase):
    pass


class PluginSchema(PluginSchema):
    inputs: List[PluginInput]
    outputs: List[PluginOutput]
    version: Version
