"""Extending automatically generated compute model.

This file modifies and extend certain fields and
functions of PolusComputeSchema.py which is automatically
generated by datamodel-codegen from JSON schema.
"""
from typing import List

from polus.plugins._plugins.io import IOBase, Version
from polus.plugins._plugins.models.PolusComputeSchema import (PluginInput,
                                                              PluginOutput,
                                                              PluginSchema)


class PluginInput(PluginInput, IOBase):
    """Base Class for Input Args."""


class PluginOutput(PluginOutput, IOBase):
    """Base Class for Output Args."""


class PluginSchema(PluginSchema):
    """Extended Compute Plugin Schema with extended IO defs."""

    inputs: List[PluginInput]
    outputs: List[PluginOutput]
    version: Version
