"""Extending automatically generated wipp model.

This file modifies and extend certain fields and
functions of WIPPPluginSchema.py which is automatically
generated by datamodel-codegen from JSON schema.
"""
from typing import List, Literal, Optional, Union

from pydantic import BaseModel, Field

from polus.plugins._plugins.io import Input, Output, Version
from polus.plugins._plugins.models.WIPPPluginSchema import WippPluginManifest


class ui1(BaseModel):
    """Base class for UI items."""

    key: str = Field(constr=r"^inputs.[a-zA-Z0-9][-a-zA-Z0-9]*$")
    title: str
    description: Optional[str]
    condition: Optional[str]
    default: Optional[Union[str, float, int, bool]]
    hidden: Optional[bool] = Field(default=False)
    bind: Optional[str]


class FieldSet(BaseModel):
    """Base class for FieldSet."""

    title: str
    fields: List[str] = Field(min_items=1, unique_items=True)


class ui2(BaseModel):
    """UI items class for fieldsets."""

    key: Literal["fieldsets"]
    fieldsets: List[FieldSet] = Field(min_items=1, unique_items=True)


class WIPPPluginManifest(WippPluginManifest):
    """Extended WIPP Plugin Schema."""

    inputs: List[Input] = Field(
        ..., description="Defines inputs to the plugin", title="List of Inputs"
    )
    outputs: List[Output] = Field(
        ..., description="Defines the outputs of the plugin", title="List of Outputs"
    )
    ui: List[Union[ui1, ui2]] = Field(..., title="Plugin form UI definition")
    version: Version
