[tool.poetry]
name = "polus-images-transforms-images-image-calculator"
version = "0.3.0-dev0"
description = ""
authors = [
    "Nicholas Schaub <nick.schaub@nih.gov>",
    "Najib Ishaq <najib.ishaq@nih.gov>",
]
readme = "README.md"
packages = [{include = "polus", from = "src"}]

[tool.poetry.dependencies]
python = ">=3.9,<3.12"
bfio = {version = "^2.4.3", extras = ["all"]}
filepattern = "^2.0.7"
typer = "^0.7.0"
tqdm = "^4.65.0"
preadator = "0.4.0.dev2"
numpy = "^2.0"

[tool.poetry.group.dev.dependencies]
pre-commit = "^3.3.3"
bump2version = "^1.0.1"
pytest = "^7.3.2"
pytest-xdist = "^3.3.1"
pytest-sugar = "^0.9.7"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
pythonpath = [
  "."
]
