"""Extending automatically generated wipp model.

This file modifies and extend certain fields and
functions of WIPPPluginSchema.py which is automatically
generated by datamodel-codegen from JSON schema.
"""
from typing import Literal
from typing import Optional
from typing import Union

from polus.plugins._plugins.io import Input
from polus.plugins._plugins.io import Output
from polus.plugins._plugins.io import Version
from polus.plugins._plugins.models.pydanticv2.WIPPPluginSchema import (
    ResourceRequirements,
)
from polus.plugins._plugins.models.pydanticv2.WIPPPluginSchema import WippPluginManifest
from pydantic import BaseModel
from pydantic import Field


class UI1(BaseModel):
    """Base class for UI items."""

    key: str = Field(constr=r"^inputs.[a-zA-Z0-9][-a-zA-Z0-9]*$")
    title: str
    description: Optional[str] = None
    condition: Optional[str] = None
    default: Optional[Union[str, float, int, bool]] = None
    hidden: Optional[bool] = Field(default=False)
    bind: Optional[str] = None


class FieldSet(BaseModel):
    """Base class for FieldSet."""

    title: str
    fields: set[str] = Field(min_length=1)


class UI2(BaseModel):
    """UI items class for fieldsets."""

    key: Literal["fieldsets"]
    fieldsets: set[FieldSet] = Field(min_length=1)


class WIPPPluginManifest(WippPluginManifest):
    """Extended WIPP Plugin Schema."""

    inputs: list[Input] = Field(
        ...,
        description="Defines inputs to the plugin",
        title="List of Inputs",
    )
    outputs: list[Output] = Field(
        ...,
        description="Defines the outputs of the plugin",
        title="List of Outputs",
    )
    ui: list[Union[UI1, UI2]] = Field(..., title="Plugin form UI definition")
    version: Version
    resourceRequirements: Optional[ResourceRequirements] = Field(  # noqa
        None,
        examples=[
            {
                "ramMin": 2048,
                "coresMin": 1,
                "cpuAVX": True,
                "cpuAVX2": False,
                "gpu": True,
                "cudaRequirements": {
                    "deviceMemoryMin": 100,
                    "cudaComputeCapability": "8.0",
                },
            },
        ],
        title="Plugin Resource Requirements",
    )
