[tool.poetry]
name = "polus-images-transforms-images-image-assembler"
version = "1.5.0-dev0"
description = "A scalable image assembler plugin."
authors = ["Nick Schaub <nick.schaub@nih.gov>", "Antoine Gerardin <antoine.gerardin@gmail.com>"]
readme = "README.md"
packages = [{include = "polus", from = "src"}]

[tool.poetry.dependencies]
python = ">=3.9,<3.12"
bfio = {version = "^2.4.3", extras = ["all"]}
filepattern = "^2.0.4"
preadator = "0.4.0.dev2"
typer = "^0.7.0"
numpy = "^2.0.0"


[tool.poetry.group.dev.dependencies]
bump2version = "^1.0.1"
flake8 = "^6.0.0"
pre-commit = "^3.2.1"
flake8-docstrings = "^1.7.0"
black = "^23.3.0"
mypy = "^1.1.1"
pytest = "^7.2.2"
ruff = "^0.0.270"
requests = "^2.31.0"
# polus-plugins = { path = "../../../", develop = false }

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
pythonpath = [
  "."
]
