FROM pytorch/pytorch:1.3-cuda10.1-cudnn7-runtime

RUN conda install flask numpy ninja pyyaml cmake cffi typing pandas dask

RUN mkdir -p /home/PCA
WORKDIR /home/PCA
COPY . .

ENTRYPOINT ["python", "PCA_SVD_SharedMemory.py"]