import json
import os
from typing import Dict, List, Tuple

import dask.array as da

os.environ["PYTORCH_ENABLE_MPS_FALLBACK"] = "1"
os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "expandable_segments:True"

import pathlib
import shutil
import numpy as np
import torch
import zarr
from argolid import PyramidGenerator3D
from ngff_zarr import (
    from_ngff_zarr,
)
from PIL import Image
from sam2.automatic_mask_generator import SAM2AutomaticMaskGenerator
from sam2.build_sam import build_sam2

CHUNK_SIZE = 1024  # Size of each chunk (1024×1024 pixels)
CHUNK_OVERLAP = 100  # Overlap between chunks (100 pixels on each side)
NUM_WORKERS = 1  # Sam2 Automatic mask segmentation cannot do batch


def create_segment_properties_info():
    """
    Create an empty segment properties info file compatible with neuroglancer format.
    """
    segment_properties = {
        "@type": "neuroglancer_segment_properties",
        "inline": {
            "ids": [],
            "properties": [
                {"id": "class", "type": "label", "values": []},
                {"id": "description", "type": "description", "values": []},
                {
                    "id": "tags",
                    "type": "tags",
                    "tags": [
                        "verified",
                        "reviewed",
                        "uncertain",
                        "automated",
                        "manual",
                        "incomplete",
                        "merged",
                        "split",
                    ],
                    "tag_descriptions": [
                        "Verified by expert annotation",
                        "Reviewed but may need additional verification",
                        "Confidence in classification is low",
                        "Generated by automated pipeline",
                        "Manually annotated",
                        "Segmentation may be incomplete",
                        "Result of merge operation",
                        "Result of split operation",
                    ],
                    "values": [],
                },
            ],
        },
    }

    return segment_properties


def get_device():
    """Get the appropriate device for the current system."""
    if torch.backends.mps.is_available():
        return torch.device("mps")
    elif torch.cuda.is_available():
        return torch.device("cuda")
    return torch.device("cpu")


def init_sam2_predictor(config_path, checkpoint_path, image_shape=None):
    device = get_device()
    model = build_sam2(config_path, checkpoint_path, device=str(device))

    return SAM2AutomaticMaskGenerator(model)


def normalize_to_uint8(array):
    if array.dtype != np.uint8:
        array_min = array.min()
        array_max = array.max()
        if array_max > array_min:
            array = ((array - array_min) * 255 / (array_max - array_min)).astype(
                np.uint8
            )
        else:
            array = np.zeros_like(array, dtype=np.uint8)
    return array


def process_chunk(chunk, predictor):
    """
    Process a single chunk of an image and generate segmentation mask.

    Args:
        chunk: Chunk of image data
        predictor: SAM2 predictor

    Returns:
        Segmentation mask for the chunk
    """
    chunk = normalize_to_uint8(chunk)

    img = Image.fromarray(chunk)

    return generate_segmentation_mask(predictor, img)


def generate_segmentation_mask(predictor, image):
    img_array = np.array(image)

    if len(img_array.shape) == 2 or (
        len(img_array.shape) == 3 and img_array.shape[2] == 1
    ):
        # Stack the single channel three times to create RGB
        img_array = np.stack([img_array] * 3, axis=-1)

    if len(img_array.shape) != 3 or img_array.shape[2] != 3:
        raise ValueError(f"Unexpected image shape: {img_array.shape}")

    with torch.inference_mode():
        masks = predictor.generate(img_array)

    height, width = img_array.shape[:2]
    label_image = np.zeros((height, width), dtype=np.uint16)

    for idx, mask in enumerate(masks, start=1):
        label_image[mask["segmentation"]] = idx

    return label_image


def initialize_job(
    output_path: pathlib.Path,
) -> Tuple[Dict, bool, List[int]]:
    """
    Creates directories and sets up progress file
    """
    resuming = output_path.exists()
    progress_file = output_path / "progress.json"

    if resuming:
        print("Found existing output directory. Attempting to resume segmentation.")
        with open(progress_file, "r") as f:
            progress = json.load(f)
        processed_slices = progress.get("processed_slices", [])
    else:
        print("Starting new segmentation job")
        output_path.mkdir(parents=True)
        processed_slices = []
        progress = {"processed_slices": processed_slices, "total_slices": 0}

    return progress, resuming, processed_slices


def initialize_zarr_store(
    output_path: pathlib.Path, original_path: pathlib.Path, dtype=np.uint16
) -> zarr.Group:
    """
    Copy the original dataset to the output location, which we will modify later
    """
    print(f"Copying original dataset from {original_path} to {output_path}")

    # Make sure output directory exists
    os.makedirs(output_path, exist_ok=True)

    # Copy the original dataset to the output location
    if os.path.exists(original_path) and original_path != output_path:
        # Copy zarr directory contents
        for item in os.listdir(original_path):
            s = os.path.join(original_path, item)
            d = os.path.join(output_path, item)
            if os.path.isdir(s):
                shutil.copytree(s, d, dirs_exist_ok=True)
            else:
                shutil.copy2(s, d)

    # Initialize segment properties
    segment_properties = create_segment_properties_info()
    info_path = output_path / "info"
    with open(info_path, "w") as f:
        json.dump(segment_properties, f, indent=2)

    # Open the zarr store at the output location
    store = zarr.DirectoryStore(str(output_path), dimension_separator="/")
    root = zarr.group(store)

    return root


def update_segment_properties(
    output_path: pathlib.Path, segmentation: np.ndarray
) -> None:
    """
    Update segment properties file with new segments from a segmentation mask.

    Args:
        output_path: Path to the output directory
        segmentation: Segmentation mask with new segments
    """
    info_path = output_path / "info"
    with open(info_path, "r") as f:
        segment_properties = json.load(f)

    # Add any new segments from this slice
    unique_ids = np.unique(segmentation)
    unique_ids = unique_ids[unique_ids > 0]

    str_ids = [str(int(id)) for id in unique_ids]
    current_str_ids = segment_properties["inline"]["ids"]

    # Add any new IDs not already in the properties
    new_ids = [id for id in str_ids if id not in current_str_ids]
    if new_ids:
        for id in new_ids:
            segment_properties["inline"]["ids"].append(id)
            segment_properties["inline"]["properties"][0]["values"].append(
                f"segment {id}"
            )
            segment_properties["inline"]["properties"][1]["values"].append(
                f"Automatically generated segment {id}"
            )
            segment_properties["inline"]["properties"][2]["values"].append(
                [3]
            )  # Automated tag

        # Write updated properties
        with open(info_path, "w") as f:
            json.dump(segment_properties, f, indent=2)


def update_progress(
    output_path: pathlib.Path,
    progress: Dict,
    processed_slices: List[int],
    slice_index: int,
) -> None:
    """
    Update the progress file with newly processed slice.

    Args:
        output_path: Path to the output directory
        progress: Progress dictionary
        processed_slices: List of processed slice indices
        slice_index: Index of the newly processed slice
    """
    if slice_index not in processed_slices:
        processed_slices.append(slice_index)
        progress["processed_slices"] = processed_slices
        progress_file = output_path / "progress.json"
        with open(progress_file, "w") as f:
            json.dump(progress, f)


def process_slice(
    volume: np.ndarray,
    slice_index: int,
    predictor: SAM2AutomaticMaskGenerator,
    zarr_root: zarr.Group,
    ndim: int,
    output_path: pathlib.Path,
    progress: Dict,
    processed_slices: List[int],
    num_slices: int,
) -> None:
    """
    Process a single slice and update zarr store.

    Args:
        volume: Volume data
        slice_index: Index of the slice to process
        predictor: SAM2 predictor
        zarr_root: Zarr root group
        ndim: Number of dimensions
        output_path: Path to the output directory
        progress: Progress dictionary
        processed_slices: List of processed slice indices
        num_slices: Total number of slices
    """
    if slice_index in processed_slices:
        print(f"Skipping already processed slice {slice_index}/{num_slices}")
        return

    # Get the slice and compute
    slice_data = volume[slice_index]
    # Check if the slice is small enough to process directly
    if slice_data.shape[0] <= CHUNK_SIZE and slice_data.shape[1] <= CHUNK_SIZE:
        slice_data = normalize_to_uint8(slice_data)
        img = Image.fromarray(slice_data)
        segmentation = generate_segmentation_mask(predictor, img)
    else:
        # For large images, use dask map_overlap to process in chunks
        print(
            f"Processing slice {slice_index} in {CHUNK_SIZE}×{CHUNK_SIZE} chunks with {CHUNK_OVERLAP} pixel overlap"
        )

        # Use map_overlap to process the image in chunks with overlap
        chunked_result = da.map_overlap(
            process_chunk,
            slice_data,
            depth={0: CHUNK_OVERLAP, 1: CHUNK_OVERLAP},
            boundary="reflect",
            dtype=np.uint16,
            chunks=(CHUNK_SIZE, CHUNK_SIZE),
            predictor=predictor,
        )

        # Compute the final result
        segmentation = chunked_result.compute(scheduler="synchronous")

    zarr_array = zarr_root["0"]
    z = zarr.open(zarr_array.store, path=zarr_array.path, mode="r+")

    # Update the specific slice in the zarr array to save progress
    if ndim == 5:  # (T, C, Z, Y, X)
        z[0, 0, slice_index] = segmentation
    else:  # (C, Z, Y, X)
        z[0, slice_index] = segmentation

    # Update segment properties
    update_segment_properties(output_path, segmentation)

    # Update progress
    update_progress(output_path, progress, processed_slices, slice_index)

    # Print progress
    if slice_index % 10 == 0 or slice_index == num_slices - 1:
        print(
            f"Processed slice {slice_index}/{num_slices} ({len(processed_slices)}/{num_slices} complete)"
        )


def autosegment_dataset(input_dir: pathlib.Path, output_path: pathlib.Path):
    progress, resuming, processed_slices = (
        initialize_job(output_path)
    )

    multiscales = from_ngff_zarr(input_dir)
    image_data = multiscales.images[0]  # Get the highest resolution image

    ndim = len(image_data.data.shape)
    print(f"Dataset shape: {image_data.data.shape}")
    print(f"Data chunks: {image_data.data.chunks}")

    # Extract the correct volume based on dimensionality
    if ndim == 5:  # Typically (T, C, Z, Y, X)
        print("5D dataset detected (T, C, Z, Y, X)")
        volume = image_data.data[0, 0]
        slice_shape = (volume[0].shape[0], volume[0].shape[1])
    elif ndim == 4:  # Typically (C, Z, Y, X)
        print("4D dataset detected (C, Z, Y, X)")
        volume = image_data.data[0]
        slice_shape = (volume[0].shape[0], volume[0].shape[1])
    else:
        raise ValueError(f"Unexpected number of dimensions: {ndim}")

    num_slices = volume.shape[0]
    print(f"Processing {num_slices} Z-slices from channel")

    if not resuming or progress.get("total_slices", 0) != num_slices:
        progress["total_slices"] = num_slices
        with open(output_path / "progress.json", "w") as f:
            json.dump(progress, f)

    sam2_predictor = init_sam2_predictor(
        "configs/sam2.1/sam2.1_hiera_s.yaml",
        "models/sam2.1_hiera_small.pt",
        image_shape=slice_shape,
    )

    if not resuming:
        root = initialize_zarr_store(
            output_path,
            input_dir,
        )
    else:
        store = zarr.DirectoryStore(str(output_path), dimension_separator="/")
        root = zarr.group(store)

    for z in range(num_slices):
        process_slice(
            volume,
            z,
            sam2_predictor,
            root,
            ndim,
            output_path,
            progress,
            processed_slices,
            num_slices,
        )

    zarr_loc_dir = str(output_path)
    base_scale_key = 0
    num_levels = len(multiscales.images)

    pyramid_gen = PyramidGenerator3D(zarr_loc_dir, base_scale_key)
    pyramid_gen.generate_pyramid(num_levels)

    # Set permissions recursively on the output directory
    print(f"Setting permissions on {output_path}")
    for root_dir, dirs, files in os.walk(str(output_path)):
        for dir_name in dirs:
            dir_path = os.path.join(root_dir, dir_name)
            os.chmod(dir_path, 0o755)

        # Set 0755 (drwxr-xr-x) permissions on files
        for file_name in files:
            file_path = os.path.join(root_dir, file_name)
            os.chmod(file_path, 0o755)


def autosegmentation(input_dir: pathlib.Path, output_dir: pathlib.Path):
    """ome_zarr_autosegmentation.

    Args:
        input_dir: input directory to process
        filepattern: filepattern to filter inputs
        output_dir: output ome-zarr directory
    Returns:
        None
    """
    autosegment_dataset(input_dir, output_dir)
    