FROM nvidia/cuda:10.1-cudnn7-devel-ubuntu18.04
FROM continuumio/anaconda3

RUN apt-get update -y  && \
    apt-get install wget -y && \
    apt-get install gcc g++ -y && \
    apt-get install git -y

RUN mkdir -p /home/PCA
WORKDIR /home/PCA
COPY . .

RUN conda install flask numpy ninja pyyaml mkl mkl-include setuptools cmake cffi typing pandas dask   && \              
    conda install -c pytorch magma-cuda101

RUN git clone --recursive https://github.com/pytorch/pytorch
WORKDIR pytorch

RUN git submodule sync && \
    git submodule update --init --recursive

ENV CMAKE_PREFIX_PATH ${CONDA_PREFIX:-"$(dirname $(which conda))/../"}
RUN python setup.py install

WORKDIR /home/PCA
CMD ["python", "PCA_SVD_SharedMemory.py", "direct", "cpu", "yes", "10.csv", "output.csv"]
