"""Run the montaging tool from the command line."""
import json
import logging
import os
import pathlib
import typing

import typer
from polus.images.transforms.images.montage import __version__
from polus.images.transforms.images.montage import generate_montage_patterns
from polus.images.transforms.images.montage import montage_all
from polus.images.transforms.images.montage.montage import MULTIPLIER
from polus.images.transforms.images.montage.montage import SPACING

app = typer.Typer()

# Initialize the logger
logging.basicConfig(
    format="%(asctime)s - %(name)-8s - %(levelname)-8s - %(message)s",
    datefmt="%d-%b-%y %H:%M:%S",
)
logger = logging.getLogger("polus.images.transforms.images.montage")
logger.setLevel(os.environ.get("POLUS_LOG", logging.INFO))


def _run(  # noqa: PLR0913
    pattern: str,
    inp_dir: pathlib.Path,
    layout: list[str],
    out_dir: pathlib.Path,
    flip_axis: list[str],
    image_spacing: int,
    grid_spacing: int,
    preview: bool,
) -> None:
    """Run montage or preview with parsed options."""
    if preview:
        preview_path = pathlib.Path(out_dir).joinpath("preview.json")
        with preview_path.open("w") as fw:
            subpatterns = generate_montage_patterns(pattern, inp_dir, layout)
            out_dir_list = [
                f"img-global-positions-{i}.txt" for i in range(len(subpatterns))
            ]
            out_files: dict[str, typing.Union[list[str], str]] = {
                r"filepattern": "img-global-positions-{p:d+}.txt",
                "outDir": out_dir_list,
            }
            json.dump(out_files, fw, indent=2)
    else:
        montage_all(
            pattern,
            inp_dir,
            layout,
            flip_axis,
            out_dir,
            image_spacing,
            grid_spacing,
        )


@app.command()
def _main(  # noqa: PLR0913
    pattern: str = typer.Option(
        ...,
        "--filePattern",
        help="FilePattern used to parse data.",
    ),
    inp_dir: pathlib.Path = typer.Option(
        ...,
        "--inpDir",
        help="Specify montage organization.",
    ),
    layout: list[str] = typer.Option(
        ...,
        "--layout",
        help="Specify montage organization.",
    ),
    out_dir: pathlib.Path = typer.Option(..., "--outDir", help="Output collection."),
    flip_axis: list[str] = typer.Option(
        [],
        "--flipAxis",
        help="Axes to flip or reverse order.",
    ),
    image_spacing: int = typer.Option(
        SPACING,
        "--imageSpacing",
        help="Spacing between images in the smallest subgrid.",
    ),
    grid_spacing: int = typer.Option(
        MULTIPLIER,
        "--gridSpacing",
        help="Spacing between values in the same grid level.",
    ),
    preview: bool = typer.Option(
        False,
        help="Output a JSON preview of files generated by this tool.",
    ),
) -> None:
    """Advanced montaging tool."""
    logger.info(f"version: {__version__}")

    # Parse the arguments
    if len(flip_axis) == 1:
        flip_axis = list(flip_axis[0])

    if len(layout) == 1:
        layout = layout[0].replace(" ", "").split(",")

    logger.info(f"filePattern = {pattern}")
    logger.info(f"inpDir = {inp_dir}")
    logger.info(f"layout = {layout}")
    logger.info(f"flipAxis = {flip_axis}")
    logger.info(f"outDir = {out_dir}")
    logger.info(f"imageSpacing = {image_spacing}")
    logger.info(f"gridSpacing = {grid_spacing}")

    _run(
        pattern,
        inp_dir,
        layout,
        out_dir,
        flip_axis,
        image_spacing,
        grid_spacing,
        preview,
    )


if __name__ == "__main__":
    app()
