[mypy]
files = src/polus/images/segmentation/cellpose_inference, tests/
exclude = \.git/
disable_error_code = import-untyped

[mypy-bfio]
ignore_missing_imports = True

[mypy-cellpose]
ignore_missing_imports = True

[mypy-cellpose.models]
ignore_missing_imports = True

[mypy-filepattern]
ignore_missing_imports = True

[mypy-tqdm]
ignore_missing_imports = True
